names(d)[names(d) == "V1"] <- "Mean Body Acc Time X"
names(d)[names(d) == "V2"] <- "Mean Body Acc Time Y"
names(d)[names(d) == "V3"] <- "Mean Body Acc Time Z"
names(d)[names(d) == "V4"] <- "Std Body Acc Time X"
names(d)[names(d) == "V5"] <- "Std Body Acc Time Y"
names(d)[names(d) == "V6"] <- "Std Body Acc Time Z"
names(d)[names(d) == "V41"] <- "Mean Gravity Acc Time X"
names(d)[names(d) == "V42"] <- "Mean Gravity Acc Time Y"
names(d)[names(d) == "V43"] <- "Mean Gravity Acc Time Z"
names(d)[names(d) == "V44"] <- "Std Gravity Acc Time X"
names(d)[names(d) == "V45"] <- "Std Gravity Acc Time Y"
names(d)[names(d) == "V46"] <- "Std Gravity Acc Time Z"
names(d)[names(d) == "V81"] <- "Mean Body Acc Jerk Time X"
names(d)[names(d) == "V82"] <- "Mean Body Acc Jerk Time Y"
names(d)[names(d) == "V83"] <- "Mean Body Acc Jerk Time Z"
names(d)[names(d) == "V84"] <- "Std Body Acc Jerk Time X"
names(d)[names(d) == "V85"] <- "Std Body Acc Jerk Time Y"
names(d)[names(d) == "V86"] <- "Std Body Acc Jerk Time Z"
names(d)[names(d) == "V121"] <- "Mean Body Gyro Time X"
names(d)[names(d) == "V122"] <- "Mean Body Gyro Time Y"
names(d)[names(d) == "V123"] <- "Mean Body Gyro Time Z"
names(d)[names(d) == "V124"] <- "Std Body Gyro Time X"
names(d)[names(d) == "V125"] <- "Std Body Gyro Time Y"
names(d)[names(d) == "V126"] <- "Std Body Gyro Time Z"
names(d)[names(d) == "V161"] <- "Mean Body Gyro Jerk Time X"
names(d)[names(d) == "V162"] <- "Mean Body Gyro Jerk Time Y"
names(d)[names(d) == "V163"] <- "Mean Body Gyro Jerk Time Z"
names(d)[names(d) == "V164"] <- "Std Body Gyro Jerk Time X"
names(d)[names(d) == "V165"] <- "Std Body Gyro Jerk Time Y"
names(d)[names(d) == "V166"] <- "Std Body Gyro Jerk Time Z"
names(d)[names(d) == "V201"] <- "Mean Body Acc Magnitude Time"
names(d)[names(d) == "V202"] <- "Std Body Acc Magnitude Time"
names(d)[names(d) == "V214"] <- "Mean Gravity Acc Magnitude Time"
names(d)[names(d) == "V215"] <- "Std Gravity Acc Magnitude Time"
names(d)[names(d) == "V227"] <- "Mean Body Acc Jerk Magnitude Time"
names(d)[names(d) == "V228"] <- "Std Body Acc Jerk Magnitude Time"
names(d)[names(d) == "V240"] <- "Mean Body Gyro Magnitude Time"
names(d)[names(d) == "V241"] <- "Std Body Gyro Magnitude Time"
names(d)[names(d) == "V253"] <- "Mean Body Gyro Jerk Magnitude Time"
names(d)[names(d) == "V254"] <- "Std Body Gyro Jerk Magnitude Time"
names(d)[names(d) == "V266"] <- "Mean Body Acc FFT X"
names(d)[names(d) == "V267"] <- "Mean Body Acc FFT Y"
names(d)[names(d) == "V268"] <- "Mean Body Acc FFT Z"
names(d)[names(d) == "V269"] <- "Std Body Acc FFT X"
names(d)[names(d) == "V270"] <- "Std Body Acc FFT Y"
names(d)[names(d) == "V271"] <- "Std Body Acc FFT Z"
names(d)[names(d) == "V345"] <- "Mean Body Acc Jerk FFT X"
names(d)[names(d) == "V346"] <- "Mean Body Acc Jerk FFT Y"
names(d)[names(d) == "V347"] <- "Mean Body Acc Jerk FFT Z"
names(d)[names(d) == "V348"] <- "Std Body Acc Jerk FFT X"
names(d)[names(d) == "V349"] <- "Std Body Acc Jerk FFT Y"
names(d)[names(d) == "V350"] <- "Std Body Acc Jerk FFT Z"
names(d)[names(d) == "V424"] <- "Mean Body Gyro FFT X"
names(d)[names(d) == "V425"] <- "Mean Body Gyro FFT Y"
names(d)[names(d) == "V426"] <- "Mean Body Gyro FFT Z"
names(d)[names(d) == "V427"] <- "Std Body Gyro FFT X"
names(d)[names(d) == "V428"] <- "Std Body Gyro FFT Y"
names(d)[names(d) == "V429"] <- "Std Body Gyro FFT Z"
names(d)[names(d) == "V503"] <- "Mean Body Acc Magnitude FFT"
names(d)[names(d) == "V504"] <- "Std Body Acc Magnitude FFT"
names(d)[names(d) == "V516"] <- "Mean Body Acc Jerk Magnitude FFT"
names(d)[names(d) == "V517"] <- "Std Body Acc Jerk Magnitude FFT"
names(d)[names(d) == "V529"] <- "Mean Body Gyro Magnitude FFT"
names(d)[names(d) == "V530"] <- "Std Body Gyro Magnitude FFT"
names(d)[names(d) == "V542"] <- "Mean Body Body Gyro Magnitude FFT"
names(d)[names(d) == "V543"] <- "Std Body Body Gyro Magnitude FFT"